package com.nilpo.contenttracker.core.model

data class AddTrackedMediaRequest(
    val type: MediaType,
    val title: String,
    val progressTotal: Int?,
    val initialStatus: TrackingStatus,
    val isOwned: Boolean,
    val ownershipType: OwnershipType,
    val platformName: String?,
    val platformType: ConsumptionPlatformType,
    val originalTitle: String? = null,
    val releaseYear: Int? = null,
    val genres: List<String> = emptyList(),
    val creators: List<String> = emptyList(),
    val credits: List<MediaCredit> = emptyList(),
    val sourceUrl: String? = null,
    val externalRating: MetadataRatingSuggestion? = null,
    val externalRatings: List<MetadataExternalRatingSuggestion> = emptyList(),
    val popularityScore: Double? = null,
    val rankingPosition: Int? = null,
    val rankingLabel: String? = null,
    val providerCollectionTitle: String? = null,
    val ratingDistributionJson: String? = null,
    val popularityJson: String? = null,
    val rankingJson: String? = null,
    val metadataSource: MetadataSource? = null,
    val metadataExternalId: String? = null,
    val coverUrl: String? = null,
    val synopsis: String? = null,
)
