package com.nilpo.contenttracker.core.model

data class MediaItem(
    val id: Long,
    val type: MediaType,
    val title: String,
    val collectionId: Long? = null,
    val collectionSortOrder: Double? = null,
    val progressTotal: Int? = null,
    val originalTitle: String? = null,
    val releaseYear: Int? = null,
    val language: String? = null,
    val genres: List<String> = emptyList(),
    val creators: List<String> = emptyList(),
    val coverUrl: String? = null,
    val synopsis: String? = null,
    val sourceUrl: String? = null,
    val steamAppId: String? = null,
    val externalRatingScore: Double? = null,
    val externalRatingMax: Double? = null,
    val externalRatingVoteCount: Int? = null,
    val primaryExternalRatingId: Long? = null,
    val popularityScore: Double? = null,
    val rankingPosition: Int? = null,
    val rankingLabel: String? = null,
    val providerCollectionTitle: String? = null,
    val ratingDistributionJson: String? = null,
    val popularityJson: String? = null,
    val rankingJson: String? = null,
    val metadataLastFetchedAtEpochMillis: Long? = null,
    val metadataExternalId: String? = null,
    val metadataSource: MetadataSource? = null,
    val malId: Int? = null,
    val isOwned: Boolean = false,
)
